config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'welcome#index'
  resources :posts do
    member do
      get 'like'
      get 'dislike'
      put 'like', to: "posts#like"
      put 'dislike', to: "posts#dislike"
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user

  validates_presence_of :blob, :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  acts_as_voter

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      if auth.info.name
        user.name = auth.info.name
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:like, :dislike]

  def create
    post = Post.new(post_params)
    unless post.save
      flash[:error] = "Post could not be shared"
    end
    redirect_to :back
  end

  def post_params
    params.require(:post).permit(:blob, :user_id)
  end

  def show
  end

  def like
    @content.liked_by current_user

    if request.xhr?
      render json: { count: @content.get_likes.size, id: params[:id] }
    else
      redirect_to :back
    end
  end

  def dislike
    @content.disliked_by current_user

    if request.xhr?
      head :ok
    else
      redirect_to :back
    end
  end

  private

  def find_post
    @content = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by(:provider => auth.provider,
                        :uid => auth.uid) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.order(:cached_votes_up).reverse
    @post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vchat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="header clearfix">
    <h3 class="text-muted">Vchat</h3>
  </div>
</div>
<div class="container">
  <div id="user-widget">
    <% if current_user %>
      Welcome <strong><%= current_user.name %></strong>!
      <div class="pull-right">
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      </div>
      <br>
      <br>
      <div class="row">
        <div class="col-md-10 col-md-offset-3">
          <%= form_for @post, method: :post do |f| %>
            <%= f.text_field :blob, class: "col-md-7", style: "height: 40px" %><br />
            <%= f.hidden_field :user_id, value: current_user.id %><br />
            <%= f.submit %>
          <% end %>
          <br>
          <% @posts.each do |post| %>
            <%= post.user.name %>
            <br>
            <%= auto_link(post.blob) %>
            <br>
            <span class="votes-count" data-id="<%= post.id %>">
              <%= post.get_likes.size %>
            </span>
            <% if current_user.liked? post %>
              <%= link_to "Dislike", dislike_post_path(post), class: 'vote', method: :put, remote: true, data: { toggle_text: 'Like', toggle_href: like_post_path(post), id: post.id } %>
            <% else %>
              <%= link_to "Like", like_post_path(post), class: 'vote', method: :put, remote: true, data: { toggle_text: 'Dislike', toggle_href: dislike_post_path(post), id: post.id } %>
            <% end %>
            <br>
            <br>
          <% end %>
        <% else %>
          <%= link_to "Login with Facebook", "/auth/facebook", id: "sign_in" %>
        <% end %>
        <br>
      </div>
    </div>
  </div>
</div>
<%= content_for :script do %>
  <%= javascript_include_tag 'voting' %>
<% end %>